"""Export the daily prices after every scanner signal to an Excel workbook.

Uses the dataset build_dataset.py stores (data/model/signals.csv +
paths.csv.gz): the signal candle and the sessions that followed it.

Sheets:
  Read me        what everything means
  Signals        one row per signal: trigger, entry (if it crossed), close
                 at 2/4/8/12 weeks after the signal, % vs trigger
  <scanner>      daily rows per signal: Day 0 = signal candle, then Open/
                 High/Low/Close per session, % close vs trigger (formula)
  Closes grid    one row per signal, daily closes across; green when the
                 close is above the trigger, red below

Usage: python export_daily_prices.py [output.xlsx]
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
from openpyxl import Workbook
from openpyxl.formatting.rule import FormulaRule
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

import breakout_sim as bs
from signal_model import load_dataset

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = ROOT / "reports" / "daily_prices_after_signal.xlsx"
SHEET_NAMES = {"63_30_daily": "63_30_daily", "Bullish_Scanner": "Bullish_Scanner", "Wkly_upswing": "Wkly_upswing"}
CHECKPOINTS = [10, 20, 40, 60]  # sessions after the signal = 2, 4, 8, 12 weeks

FONT = Font(name="Arial", size=10)
BOLD = Font(name="Arial", size=10, bold=True)
HEADER_FILL = PatternFill("solid", start_color="DDE4EE")
GREEN = PatternFill("solid", start_color="C6EFCE")
RED = PatternFill("solid", start_color="FFC7CE")
PRICE = "#,##0.00"
PCT = "0.0%;-0.0%;0.0%"
DATE = "dd-mmm-yyyy"


def _header(ws, headers, widths):
    ws.append(headers)
    for i, (h, w) in enumerate(zip(headers, widths), start=1):
        c = ws.cell(row=1, column=i)
        c.font, c.fill = BOLD, HEADER_FILL
        c.alignment = Alignment(wrap_text=True, vertical="center")
        ws.column_dimensions[get_column_letter(i)].width = w
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(headers))}1"


def _style_row(ws, row, formats):
    for col, fmt in formats.items():
        cell = ws.cell(row=row, column=col)
        cell.font = FONT
        if fmt:
            cell.number_format = fmt


def build_workbook(signals: pd.DataFrame, paths: dict[int, pd.DataFrame]) -> Workbook:
    ok = signals[signals["data_status"] == "ok"].sort_values(["scanner_name", "signal_date", "symbol"])
    wb = Workbook()

    # --- Read me -----------------------------------------------------------
    ws = wb.active
    ws.title = "Read me"
    notes = [
        ("Daily prices after each Chartink scanner signal", BOLD),
        ("", FONT),
        ("Source: Chartink backtest exports in data/backtest/*.csv (signal dates) and Yahoo Finance daily "
         "NSE prices, fetched by scripts/build_dataset.py. Generated by scripts/export_daily_prices.py.", FONT),
        ("", FONT),
        ("Day 0 = the signal candle: the hit date's candle for the daily scanners, the completed week's "
         "candle for Wkly_upswing (Chartink dates weekly hits by the week's first day).", FONT),
        ("Trigger price = high of the signal candle. Signal low / close = its low and close.", FONT),
        (f"Day 1, 2, ... = the trading sessions after the signal candle, up to {bs.FORWARD_DAYS}.", FONT),
        (f"Entry = first session within {bs.DAILY_ENTRY_WINDOW} sessions ({bs.WEEKLY_ENTRY_WINDOW} for weekly) whose high "
         "went above the trigger. Entry price = the trigger, or the open if it gapped above.", FONT),
        ("% vs trigger = close / trigger price - 1 (a formula, so it updates if you edit a price).", FONT),
        ("Signals sheet: close at day 10 / 20 / 40 / 60 = about 2 / 4 / 8 / 12 weeks after the signal. "
         "Blank = that day hasn't happened yet.", FONT),
        ("Closes grid: green = close above the trigger, red = below.", FONT),
        ("", FONT),
        ("Caveats: prices are not adjusted for every corporate action (e.g. TRIVENI's drop on "
         "22-Jul-2026 looks like one). Symbols Yahoo doesn't carry are left out.", FONT),
    ]
    for text, font in notes:
        ws.append([text])
        ws.cell(row=ws.max_row, column=1).font = font
    ws.column_dimensions["A"].width = 120
    missing = signals[signals["data_status"] != "ok"]
    if not missing.empty:
        ws.append([f"No price data for: {', '.join(sorted(missing['symbol'].unique()))}"])
        ws.cell(row=ws.max_row, column=1).font = FONT

    # --- Daily sheets (written first so Signals can reference them) ---------
    daily_rows: dict[int, tuple[str, int]] = {}  # hit_id -> (sheet, row of Day 0)
    for scanner, sheet in SHEET_NAMES.items():
        grp = ok[ok["scanner_name"] == scanner]
        if grp.empty:
            continue
        ws = wb.create_sheet(sheet)
        _header(ws, ["Symbol", "Signal date", "Trigger price", "Day", "Date", "Open", "High", "Low",
                     "Close", "% vs trigger", "Entry"],
                [13, 12, 10, 6, 12, 10, 10, 10, 10, 10, 18])
        fmts = {1: None, 2: DATE, 3: PRICE, 4: "0", 5: DATE, 6: PRICE, 7: PRICE, 8: PRICE, 9: PRICE, 10: PCT, 11: None}
        r = 1  # openpyxl's max_row rescans the sheet, so count rows ourselves
        for _, s in grp.iterrows():
            path = paths.get(s["hit_id"], pd.DataFrame(columns=["Open", "High", "Low", "Close"]))
            entry = bs.find_entry(path["Open"].to_numpy(), path["High"].to_numpy(), s["trigger"],
                                  bs.entry_window_for(scanner))
            sig_date = s["signal_date"].to_pydatetime()
            r += 1
            daily_rows[s["hit_id"]] = (sheet, r)
            ws.append([s["symbol"], sig_date, s["trigger"], 0, sig_date, None, s["trigger"], s["bar_low"],
                       s["bar_close"], f"=I{r}/C{r}-1", "signal candle"])
            _style_row(ws, r, fmts)
            for k, bar in enumerate(path.itertuples(), start=1):
                r += 1
                mark = ""
                if entry is not None and entry[0] == k - 1:
                    mark = f"BUY @ {entry[1]:.2f}"
                ws.append([s["symbol"], sig_date, s["trigger"], k, bar.Index.to_pydatetime(), bar.Open, bar.High,
                           bar.Low, bar.Close, f"=I{r}/C{r}-1", mark])
                _style_row(ws, r, fmts)
                if mark:
                    ws.cell(row=r, column=11).font = BOLD

    # --- Signals summary ----------------------------------------------------
    ws = wb.create_sheet("Signals", 1)
    cp_headers = []
    for n in CHECKPOINTS:
        cp_headers += [f"Close day {n} (~{n // 5}w)", f"% vs trigger day {n}"]
    _header(ws, ["Scanner", "Symbol", "Market cap", "Sector", "Signal date", "Trigger price", "Signal low",
                 "Signal close", "Crossed trigger?", "Entry date", "Entry price", "Days of data"] + cp_headers,
            [15, 13, 10, 18, 12, 10, 10, 10, 9, 12, 10, 8] + [11, 10] * len(CHECKPOINTS))
    fmts = {1: None, 2: None, 3: None, 4: None, 5: DATE, 6: PRICE, 7: PRICE, 8: PRICE, 9: None, 10: DATE,
            11: PRICE, 12: "0"}
    for i in range(len(CHECKPOINTS)):
        fmts[13 + 2 * i], fmts[14 + 2 * i] = PRICE, PCT
    r = 1
    for _, s in ok.iterrows():
        path = paths.get(s["hit_id"], pd.DataFrame(columns=["Open", "High", "Low", "Close"]))
        entry = bs.find_entry(path["Open"].to_numpy(), path["High"].to_numpy(), s["trigger"],
                              bs.entry_window_for(s["scanner_name"]))
        r += 1
        row = [s["scanner_name"], s["symbol"], s["marketcap"], s["sector"], s["signal_date"].to_pydatetime(),
               s["trigger"], s["bar_low"], s["bar_close"], "Yes" if entry else "No",
               path.index[entry[0]].to_pydatetime() if entry else None, entry[1] if entry else None, len(path)]
        sheet, day0 = daily_rows[s["hit_id"]]
        for i, n in enumerate(CHECKPOINTS):
            if n <= len(path):
                close_col = get_column_letter(len(row) + 1)
                row += [f"='{sheet}'!I{day0 + n}", f"={close_col}{r}/F{r}-1"]
            else:
                row += [None, None]
        ws.append(row)
        _style_row(ws, r, fmts)

    # --- Closes grid --------------------------------------------------------
    ws = wb.create_sheet("Closes grid")
    days = list(range(1, bs.FORWARD_DAYS + 1))
    _header(ws, ["Scanner", "Symbol", "Signal date", "Trigger price"] + [f"Day {d}" for d in days],
            [15, 13, 12, 10] + [8] * len(days))
    ws.freeze_panes = "E2"
    r = 1
    for _, s in ok.iterrows():
        closes = paths.get(s["hit_id"], pd.DataFrame(columns=["Close"]))["Close"].tolist()
        ws.append([s["scanner_name"], s["symbol"], s["signal_date"].to_pydatetime(), s["trigger"]] + closes)
        r += 1
        _style_row(ws, r, {1: None, 2: None, 3: DATE, 4: PRICE, **{c: PRICE for c in range(5, 5 + len(closes))}})
    last_col, last_row = get_column_letter(4 + len(days)), r
    area = f"E2:{last_col}{last_row}"
    ws.conditional_formatting.add(area, FormulaRule(formula=["AND(E2<>\"\",E2>$D2)"], fill=GREEN))
    ws.conditional_formatting.add(area, FormulaRule(formula=["AND(E2<>\"\",E2<=$D2)"], fill=RED))
    return wb


def main() -> int:
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUT
    signals, paths = load_dataset()
    wb = build_workbook(signals, paths)
    out.parent.mkdir(parents=True, exist_ok=True)
    wb.save(out)
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
